---
language: ruby
cache: bundler
dist: bionic
rvm:
- 2.4.9
- 2.5.8
- 2.6.6
- 2.7.2
- 3.0.0
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
notifications:
  email: false
deploy:
  provider: rubygems
  api_key:
    secure: Le2jt7XgTNh4+bKowfxAN59/QVCKnYovRHei3pqMgKLq4wT3JywP01kzG0gqkQ4OMj3Flje14nTZ7ZEGxAeuhtdSB1QSDelZ9gt1f6Smug6zJQrqDoKBRzoAeU3YmEO5QRIBDAMczMP0dg7PbfxHS8SH9qzn/ZI6oOQ7ml967te04/eODvFq4+pqmobYVQPCS1JqRUpByDhXGVxMcjSBjO1VhEk+8LJUFLup2ikmHbQSG89qKe2fJ0IX3TZhMwI9OAvhONxP7TezB87nGS48Nj/EkAb8FaZ+Bwk4V4KknNdB4Il2ikmORtNOkWeGg9vIDDGizVGsXIVeUxHKjV/Iucz4lmJHeiHmGASsJbh1Ts3dzpJen9J42fYDXJEYYmBhx2fzIwOn70bqK5ZevrzjLHcW4NoPczK7eS902VRIPYQOW46QGe3N1xzj1CZ9+/hpjUm7ffqzumzsoo95HajHsYUWAk7xftR2MMqiJu0aUiqmRvu3rfmd+9ufOqHBcdrBsA8Ad9MCdilc2R61AZ8UQ/Z0lXIz1Z+nQUBRxEpwDFgNWBk1Hp6NvMgAnU5hzwykHNxrV50CX98z+a3OPbtiQChiVydC6pTYGqBjC5RQ53UYyz7aaXGnhrewXc7wfbQerbmSdRA3TQiSEpKWvH8c8BvU5JJCeZT8baM6DemxdV8=
  gem: quirc
  on:
    tags: true
